{
  "swagger" : "2.0",
  "info" : {
    "description" : "Envision Company returns API",
    "version" : "1.0.0",
    "title" : "Envision",
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/Envision5/Envision/1.0.0",
  "tags" : [ {
    "name" : "Public",
    "description" : "Operations available to anyone"
  } ],
  "schemes" : [ "https", "http" ],
  "paths" : {
    "/v1.0" : {
      "get" : {
        "tags" : [ "Public" ],
        "summary" : "Get company returns information",
        "description" : "Get information about a particular companies returns.\n",
        "operationId" : "companyReturns",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "instrument_id",
          "in" : "query",
          "description" : "The tickers of financial instruments, in Reuters Instrument Code (e.g. CBA.AX) or natural ticker format (e.g. ASX:CBA). Comma seperated.",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "date_of_interest",
          "in" : "query",
          "description" : "The desired date of interest.",
          "required" : true,
          "type" : "string",
          "format" : "YYYY-MM-DD"
        }, {
          "name" : "list_of_var",
          "in" : "query",
          "description" : "Request for Cumulative Return and/or Average Return.",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "lower_window",
          "in" : "query",
          "description" : "The number of days before the date of interest to include in the query.",
          "required" : true,
          "type" : "integer",
          "minimum" : 0
        }, {
          "name" : "upper_window",
          "in" : "query",
          "description" : "The number of days after the date of interest to include in the query.",
          "required" : true,
          "type" : "integer",
          "minimum" : 0
        } ],
        "responses" : {
          "200" : {
            "description" : "Company returns data and metadata",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "inline_response_200_Metadata" : {
      "properties" : {
        "elapsed_time" : {
          "type" : "string",
          "example" : "4255.30ms"
        },
        "end_time" : {
          "type" : "string",
          "example" : "2018-03-30T12:38:24.000Z"
        },
        "module" : {
          "type" : "string",
          "example" : "Envision_API v1.0"
        },
        "parameters" : {
          "$ref" : "#/definitions/inline_response_200_Metadata_parameters"
        },
        "start_time" : {
          "type" : "string",
          "example" : "2018-03-30T12:38:20.000Z"
        },
        "success" : {
          "type" : "boolean",
          "example" : true
        },
        "team" : {
          "type" : "string",
          "example" : "Envision"
        },
        "error_messages" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "example" : "Error: 'Time Series (Daily)'"
          }
        }
      },
      "example" : {
        "start_time" : "2018-03-30T12:38:20.000Z",
        "success" : true,
        "module" : "Envision_API v1.0",
        "elapsed_time" : "4255.30ms",
        "end_time" : "2018-03-30T12:38:24.000Z",
        "team" : "Envision",
        "parameters" : {
          "list_of_var" : [ "Return", "Return" ],
          "upper_window" : 5.0,
          "date_of_interest" : "2012-12-10T00:00:00.000Z",
          "instrument_id" : "ABP.AX",
          "lower_window" : 3.0
        },
        "error_messages" : [ "Error: 'Time Series (Daily)'", "Error: 'Time Series (Daily)'" ]
      }
    },
    "inline_response_200" : {
      "properties" : {
        "Company_Returns" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/inline_response_200_Company_Returns"
          }
        },
        "Metadata" : {
          "$ref" : "#/definitions/inline_response_200_Metadata"
        }
      },
      "example" : {
        "Company_Returns" : [ {
          "data" : [ {
            "date" : "2012-12-07",
            "Volume_pct" : 0.13135290615687387,
            "AV_Return" : 0.0022222222222222244,
            "CM_Return" : 0.020000000000000018,
            "Return" : 0,
            "CM_Return_pct" : 0.010226569931254703,
            "Volume" : 311761.0,
            "AV_Return_pct" : 0.0011362855479171892,
            "Return_pct" : 0.0,
            "Daily_Spread" : 0.024900000000000144,
            "Relative_Date" : -3.0
          }, {
            "date" : "2012-12-07",
            "Volume_pct" : 0.13135290615687387,
            "AV_Return" : 0.0022222222222222244,
            "CM_Return" : 0.020000000000000018,
            "Return" : 0,
            "CM_Return_pct" : 0.010226569931254703,
            "Volume" : 311761.0,
            "AV_Return_pct" : 0.0011362855479171892,
            "Return_pct" : 0.0,
            "Daily_Spread" : 0.024900000000000144,
            "Relative_Date" : -3.0
          } ],
          "instrument_id" : "ABP.AX"
        }, {
          "data" : [ {
            "date" : "2012-12-07",
            "Volume_pct" : 0.13135290615687387,
            "AV_Return" : 0.0022222222222222244,
            "CM_Return" : 0.020000000000000018,
            "Return" : 0,
            "CM_Return_pct" : 0.010226569931254703,
            "Volume" : 311761.0,
            "AV_Return_pct" : 0.0011362855479171892,
            "Return_pct" : 0.0,
            "Daily_Spread" : 0.024900000000000144,
            "Relative_Date" : -3.0
          }, {
            "date" : "2012-12-07",
            "Volume_pct" : 0.13135290615687387,
            "AV_Return" : 0.0022222222222222244,
            "CM_Return" : 0.020000000000000018,
            "Return" : 0,
            "CM_Return_pct" : 0.010226569931254703,
            "Volume" : 311761.0,
            "AV_Return_pct" : 0.0011362855479171892,
            "Return_pct" : 0.0,
            "Daily_Spread" : 0.024900000000000144,
            "Relative_Date" : -3.0
          } ],
          "instrument_id" : "ABP.AX"
        } ],
        "Metadata" : {
          "start_time" : "2018-03-30T12:38:20.000Z",
          "success" : true,
          "module" : "Envision_API v1.0",
          "elapsed_time" : "4255.30ms",
          "end_time" : "2018-03-30T12:38:24.000Z",
          "team" : "Envision",
          "parameters" : {
            "list_of_var" : [ "Return", "Return" ],
            "upper_window" : 5.0,
            "date_of_interest" : "2012-12-10T00:00:00.000Z",
            "instrument_id" : "ABP.AX",
            "lower_window" : 3.0
          },
          "error_messages" : [ "Error: 'Time Series (Daily)'", "Error: 'Time Series (Daily)'" ]
        }
      }
    },
    "inline_response_200_Company_Returns" : {
      "properties" : {
        "instrument_id" : {
          "type" : "string",
          "example" : "ABP.AX"
        },
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/inline_response_200_data"
          }
        }
      },
      "example" : {
        "data" : [ {
          "date" : "2012-12-07",
          "Volume_pct" : 0.13135290615687387,
          "AV_Return" : 0.0022222222222222244,
          "CM_Return" : 0.020000000000000018,
          "Return" : 0,
          "CM_Return_pct" : 0.010226569931254703,
          "Volume" : 311761.0,
          "AV_Return_pct" : 0.0011362855479171892,
          "Return_pct" : 0.0,
          "Daily_Spread" : 0.024900000000000144,
          "Relative_Date" : -3.0
        }, {
          "date" : "2012-12-07",
          "Volume_pct" : 0.13135290615687387,
          "AV_Return" : 0.0022222222222222244,
          "CM_Return" : 0.020000000000000018,
          "Return" : 0,
          "CM_Return_pct" : 0.010226569931254703,
          "Volume" : 311761.0,
          "AV_Return_pct" : 0.0011362855479171892,
          "Return_pct" : 0.0,
          "Daily_Spread" : 0.024900000000000144,
          "Relative_Date" : -3.0
        } ],
        "instrument_id" : "ABP.AX"
      }
    },
    "inline_response_200_data" : {
      "properties" : {
        "date" : {
          "type" : "string",
          "example" : "2012-12-07"
        },
        "AV_Return" : {
          "type" : "number",
          "example" : 0.0022222222222222244
        },
        "AV_Return_pct" : {
          "type" : "number",
          "example" : 0.0011362855479171892
        },
        "CM_Return" : {
          "type" : "number",
          "example" : 0.020000000000000018
        },
        "CM_Return_pct" : {
          "type" : "number",
          "example" : 0.010226569931254703
        },
        "Daily_Spread" : {
          "type" : "number",
          "example" : 0.024900000000000144
        },
        "Relative_Date" : {
          "type" : "number",
          "example" : -3.0
        },
        "Return" : {
          "type" : "integer",
          "example" : 0
        },
        "Return_pct" : {
          "type" : "number",
          "example" : 0.0
        },
        "Volume" : {
          "type" : "number",
          "example" : 311761.0
        },
        "Volume_pct" : {
          "type" : "number",
          "example" : 0.13135290615687387
        }
      },
      "example" : {
        "date" : "2012-12-07",
        "Volume_pct" : 0.13135290615687387,
        "AV_Return" : 0.0022222222222222244,
        "CM_Return" : 0.020000000000000018,
        "Return" : 0,
        "CM_Return_pct" : 0.010226569931254703,
        "Volume" : 311761.0,
        "AV_Return_pct" : 0.0011362855479171892,
        "Return_pct" : 0.0,
        "Daily_Spread" : 0.024900000000000144,
        "Relative_Date" : -3.0
      }
    },
    "inline_response_200_Metadata_parameters" : {
      "properties" : {
        "date_of_interest" : {
          "type" : "string",
          "example" : "2012-12-10T00:00:00.000Z"
        },
        "instrument_id" : {
          "type" : "string",
          "example" : "ABP.AX"
        },
        "list_of_var" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "example" : "Return"
          }
        },
        "lower_window" : {
          "type" : "number",
          "example" : 3.0
        },
        "upper_window" : {
          "type" : "number",
          "example" : 5.0
        }
      },
      "example" : {
        "list_of_var" : [ "Return", "Return" ],
        "upper_window" : 5.0,
        "date_of_interest" : "2012-12-10T00:00:00.000Z",
        "instrument_id" : "ABP.AX",
        "lower_window" : 3.0
      }
    }
  }
}